# Generated by Django 5.1 on 2024-08-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_description', models.TextField(max_length=540)),
                ('image', models.ImageField(upload_to='images/')),
                ('live_page', models.URLField(blank=True)),
                ('github_repo', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('detailed_description', models.TextField(blank=True, max_length=2000)),
            ],
        ),
    ]
