# Generated by Django 5.1 on 2024-08-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='image',
            new_name='header_image',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='other_media',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
